### PR TITLE
sonarqube integration

### PR DESCRIPTION
**Pull request by dzlab**
This is an attempt to enable the use of SonarQube.com for quality analysis #116.
To set the values for the needed environment variables in Travis follow this [documentation](https://docs.travis-ci.com/user/sonarqube/#Inspecting-code-with-the-SonarQube-Scanner):
- `SONAR_ORGANIZATION`: name of the organisation in Sonarqube
- `SONAR_TOKEN`: the token generated in Sonarqube
- `GITHUB_TOKEN`: (to be able to run sonar on pull requests) github personal access token [doc](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)

### CODE REVIEW

**Comment by mvitz** [comment]
Thanks for your contribution.

I will take a look into this PR at the weekend if no one else does this before.

I integrated sonar some time ago for another project by using the maven way. Maybe https://github.com/innoq/spring-boot-actuator-extensions/blob/master/.travis.yml and can help as a source of inspiration as well https://github.com/innoq/spring-boot-actuator-extensions/blob/master/bin/travis.sh

**Comment by dzlab** [comment]
Yep maven sonar plugin is a second option to integrate with SonarQube.com.
Travis CI also [documented](https://docs.travis-ci.com/user/sonarqube/#SonarQube-Scanner-for-Maven) how to set it up and use it.

**Comment by fbiville** [comment]
Hey, shall we merge and see? @mvitz :)

**Comment by mvitz** [comment]
What could possibly go wrong? ;-)

Keep in mind that we (in this case you) need to create a sonarqube account and add the required configuration keys to it and to travis.

**Comment by fbiville** [comment]
@fpavageau would you have any time to look at this? 👼

**Comment by fbiville** [comment]
Finally merged, merry xmas 🎅 🍾 🕺 https://github.com/liquigraph/liquigraph/commit/86eb4d087c2d996982cf3dab726a514376ffe20a

**Pull request closed without merging**
