### PR TITLE
[#129] Roll back connection if errors occur

### PR DESCRIPTION
**Pull request by fbiville**
So currently, something weird is happening. even if we try to clean up the lock node by properly closing the failing write connection (see `LockableConnection#close`), the transaction that is supposed to delete the lock ends up being rolled back and an SQL Exception occurs with the following root cause: `javax.transaction.RollbackException: Tx status is: STATUS_MARKED_ROLLBACK`.

It is not clear yet why the lock deletion transaction is marked as such.

### CODE REVIEW

**Comment by fbiville** [comment]
Interestingly, the debugger shows that the node lock deletion tx is not top level, while it should intuitively be. Maybe it ends up being nested in the previous failing statement tx, but that does not make sense given how the code is.

**Comment by fbiville** [comment]
OK, I'm now 100% sure the statement and the lock node transactions share the same top-level transaction (debug TopLevelTransaction#markAsRollbackOnly and enter `this.transactionManager.getTransaction()`), you'll see the same tx twice.

**Comment by fbiville** [comment]
A night of sleep later, I kinda remember [this bug](https://github.com/neo4j-contrib/neo4j-jdbc-2x/issues/55) from the (legacy) JDBC driver itself and why we had to introduce the hack `KeepAliveConnection` in tests.

If we switch to using the special test instance of `liquigraph` in the test, we get another error: the connection is not closed at the end and should be. 

Anyway, I think it is time to try to solve the root issue in the legacy JDBC driver and get rid of these hacks `FixedConnectionConnector` and `KeepAliveConnection`.

**Comment by agre1981** [comment]
Hello, i fixed the problem in my project with rollback.
AssetChangelogGraphWriter.java
```
        private StatementExecution executeStatement(Changeset changeset) { ...
            } catch (SQLException e) {
                try {
                    // fix for unlocking DB for error in update statement
                    // now transaction has status Status.STATUS_MARKED_ROLLBACK and during lock removing
                    // it causes Exception TransactionFailureException: Unable to commit transaction
                    // Registered issue:  https://github.com/fbiville/liquigraph/issues/129
                    writeConnection.rollback(); 
                } catch (SQLException e1) {
                    e1.printStackTrace();
                }
                throw propagate(e);
            }
```

**Comment by fbiville** [comment]
The weird part is that in my understanding, closing a connection without rolling back or committing explicitly (with autocommit off) would result in a rollback. 
This is apparently not the case. I will try your fix.

**Comment by fbiville** [comment]
Sadly, the fix does not work 100% reliably and that's for a (rare enough?) case when the migration is invalid anyway?
I'm afraid neither @fpavageau and I have enough time to work on this for now.
@agre1981 if you think this is critical enough, please ping us and we'll find a way to handle this. For now, I'll just close this.

**Comment by agre1981** [comment]
Hello, 
1/ i think the issue is critical. Liquigraph has no use if it locks DB. In my opinion we should fix the issue or remove "locking" functionality until the issue is resoled.
2/ could you provide more information why the fix does not work? It is successfully working in my project... 
3/ the configuration with "withGraphDatabaseService()" does not work also. It's for liquigraph 2.0.1
```
        org.liquigraph.core.configuration.Configuration configuration = new ConfigurationBuilder()
                .withMasterChangelogLocation("changelog.xml")
                .withGraphDatabaseService(graphDatabaseService)
                .withRunMode().build();
```
thanks, Alex!

**Comment by fbiville** [comment]
@agre1981 the fix triggered some errors in the build for some versions.
Let's reopen the issue then, but I cannot guarantee when this will be merged. We need to find something that works on all versions of Neo4j 2.x.

**Comment by fbiville** [comment]
@agre1981 would you mind having a look at https://travis-ci.org/fbiville/liquigraph/builds/184154345?
Clearly, something breaks in some Neo4j versions with this fix, that's why it has not been merged yet.
Neither @fpavageau nor I have much time at the moment so any help would be appreciated!

**Comment by fbiville** [comment]
⚠️ branches have switch `master` is now for Neo4j 3.x, `2.x` for Neo4j 2.x.
Need to redo this PR.

**Pull request closed without merging**
