### PR TITLE
add .editorconfig and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by fagossa**
Handles [Issues-51](https://github.com/liquigraph/liquigraph/issues/51).

### CODE REVIEW

**Comment by fbiville** [comment]
Aaaaah, super! Je vais merger ASAP.

**Comment by mvitz** [comment]
Thanks for your contribution!

Maybe it would be nice to specify some more file types (e.g. *.xml)? And I personally like the `.editorconfig` for each type sorted by alphabet.

**Comment by fagossa** [comment]
Hello @mvitz , 
I've just sorted the entries and added some default settings for `xml` and `md`.

**Comment by mvitz** [comment]
Looks good to me. I would vote for a merge!

**Comment by fbiville** [comment]
Finally merged in master and 2.x, with minor changes. Thanks a lot!

**Pull request closed without merging**
