### PR TITLE
412: Migrate Spring-boot module tests to testcontainers

### PR DESCRIPTION
**Pull request by AElMehdi**

### CODE REVIEW

**Comment by fbiville** [comment]
I'm not sure I'm understanding the first commit. All required classes (`ParameterizedDatabaseIT`) should already be in the testing module.

**Comment by fbiville** [comment]
@AElMehdi please start with the `master` branch instead of `3.x`, I'll take care of correctly populating the testing module there.

**Comment by AElMehdi** [comment]
@fbiville, done!

**Review by fbiville — CHANGES_REQUESTED** [review]
`LiquigraphAutoconfigurationTest#jdbcUrl` calls should be replaced by `uri`.

**Pull request closed without merging**
